<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
			['id' => '1','short_name' => 'AF','name' => 'Afghanistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '2','short_name' => 'AL','name' => 'Albania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '3','short_name' => 'DZ','name' => 'Algeria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '4','short_name' => 'DS','name' => 'American Samoa','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '5','short_name' => 'AD','name' => 'Andorra','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '6','short_name' => 'AO','name' => 'Angola','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '7','short_name' => 'AI','name' => 'Anguilla','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '8','short_name' => 'AQ','name' => 'Antarctica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '9','short_name' => 'AG','name' => 'Antigua and/or Barbuda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '10','short_name' => 'AR','name' => 'Argentina','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '11','short_name' => 'AM','name' => 'Armenia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '12','short_name' => 'AW','name' => 'Aruba','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '13','short_name' => 'AU','name' => 'Australia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '14','short_name' => 'AT','name' => 'Austria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '15','short_name' => 'AZ','name' => 'Azerbaijan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '16','short_name' => 'BS','name' => 'Bahamas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '17','short_name' => 'BH','name' => 'Bahrain','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '18','short_name' => 'BD','name' => 'Bangladesh','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '19','short_name' => 'BB','name' => 'Barbados','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '20','short_name' => 'BY','name' => 'Belarus','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '21','short_name' => 'BE','name' => 'Belgium','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '22','short_name' => 'BZ','name' => 'Belize','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '23','short_name' => 'BJ','name' => 'Benin','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '24','short_name' => 'BM','name' => 'Bermuda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '25','short_name' => 'BT','name' => 'Bhutan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '26','short_name' => 'BO','name' => 'Bolivia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '27','short_name' => 'BA','name' => 'Bosnia and Herzegovina','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '28','short_name' => 'BW','name' => 'Botswana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '29','short_name' => 'BV','name' => 'Bouvet Island','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '30','short_name' => 'BR','name' => 'Brazil','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '31','short_name' => 'IO','name' => 'British lndian Ocean Territory','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '32','short_name' => 'BN','name' => 'Brunei Darussalam','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '33','short_name' => 'BG','name' => 'Bulgaria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '34','short_name' => 'BF','name' => 'Burkina Faso','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '35','short_name' => 'BI','name' => 'Burundi','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '36','short_name' => 'KH','name' => 'Cambodia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '37','short_name' => 'CM','name' => 'Cameroon','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '38','short_name' => 'CA','name' => 'Canada','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '39','short_name' => 'CV','name' => 'Cape Verde','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '40','short_name' => 'KY','name' => 'Cayman Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '41','short_name' => 'CF','name' => 'Central African Republic','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '42','short_name' => 'TD','name' => 'Chad','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '43','short_name' => 'CL','name' => 'Chile','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '44','short_name' => 'CN','name' => 'China','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '45','short_name' => 'CX','name' => 'Christmas Island','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '46','short_name' => 'CC','name' => 'Cocos (Keeling) Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '47','short_name' => 'CO','name' => 'Colombia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '48','short_name' => 'KM','name' => 'Comoros','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '49','short_name' => 'CG','name' => 'Congo','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '50','short_name' => 'CK','name' => 'Cook Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '51','short_name' => 'CR','name' => 'Costa Rica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '52','short_name' => 'HR','name' => 'Croatia (Hrvatska)','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '53','short_name' => 'CU','name' => 'Cuba','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '54','short_name' => 'CY','name' => 'Cyprus','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '55','short_name' => 'CZ','name' => 'Czech Republic','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '56','short_name' => 'DK','name' => 'Denmark','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '57','short_name' => 'DJ','name' => 'Djibouti','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '58','short_name' => 'DM','name' => 'Dominica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '59','short_name' => 'DO','name' => 'Dominican Republic','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '60','short_name' => 'TP','name' => 'East Timor','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '61','short_name' => 'EC','name' => 'Ecuador','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '62','short_name' => 'EG','name' => 'Egypt','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '63','short_name' => 'SV','name' => 'El Salvador','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '64','short_name' => 'GQ','name' => 'Equatorial Guinea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '65','short_name' => 'ER','name' => 'Eritrea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '66','short_name' => 'EE','name' => 'Estonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '67','short_name' => 'ET','name' => 'Ethiopia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '68','short_name' => 'FK','name' => 'Falkland Islands (Malvinas)','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '69','short_name' => 'FO','name' => 'Faroe Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '70','short_name' => 'FJ','name' => 'Fiji','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '71','short_name' => 'FI','name' => 'Finland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '72','short_name' => 'FR','name' => 'France','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '73','short_name' => 'FX','name' => 'France, Metropolitan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '74','short_name' => 'GF','name' => 'French Guiana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '75','short_name' => 'PF','name' => 'French Polynesia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '76','short_name' => 'TF','name' => 'French Southern Territories','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '77','short_name' => 'GA','name' => 'Gabon','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '78','short_name' => 'GM','name' => 'Gambia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '79','short_name' => 'GE','name' => 'Georgia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '80','short_name' => 'DE','name' => 'Germany','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '81','short_name' => 'GH','name' => 'Ghana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '82','short_name' => 'GI','name' => 'Gibraltar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '83','short_name' => 'GR','name' => 'Greece','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '84','short_name' => 'GL','name' => 'Greenland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '85','short_name' => 'GD','name' => 'Grenada','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '86','short_name' => 'GP','name' => 'Guadeloupe','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '87','short_name' => 'GU','name' => 'Guam','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '88','short_name' => 'GT','name' => 'Guatemala','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '89','short_name' => 'GN','name' => 'Guinea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '90','short_name' => 'GW','name' => 'Guinea-Bissau','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '91','short_name' => 'GY','name' => 'Guyana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '92','short_name' => 'HT','name' => 'Haiti','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '93','short_name' => 'HM','name' => 'Heard and Mc Donald Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '94','short_name' => 'HN','name' => 'Honduras','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '95','short_name' => 'HK','name' => 'Hong Kong','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '96','short_name' => 'HU','name' => 'Hungary','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '97','short_name' => 'IS','name' => 'Iceland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '98','short_name' => 'IN','name' => 'India','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '99','short_name' => 'ID','name' => 'Indonesia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '100','short_name' => 'US','name' => 'United state of America','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '101','short_name' => 'IQ','name' => 'Iraq','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '102','short_name' => 'IR','name' => 'جمهوری اسلامی ایران','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '103','short_name' => 'IE','name' => 'Ireland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '104','short_name' => 'IL','name' => 'Israel','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '105','short_name' => 'IT','name' => 'Italy','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '106','short_name' => 'CI','name' => 'Ivory Coast','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '107','short_name' => 'JM','name' => 'Jamaica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '108','short_name' => 'JP','name' => 'Japan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '109','short_name' => 'JO','name' => 'Jordan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '110','short_name' => 'KZ','name' => 'Kazakhstan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '111','short_name' => 'KE','name' => 'Kenya','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '112','short_name' => 'KI','name' => 'Kiribati','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '113','short_name' => 'KP','name' => 'Korea, Democratic People\'s Republic of','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '114','short_name' => 'KR','name' => 'Korea, Republic of','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '115','short_name' => 'XK','name' => 'Kosovo','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '116','short_name' => 'KW','name' => 'Kuwait','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '117','short_name' => 'KG','name' => 'Kyrgyzstan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '118','short_name' => 'LA','name' => 'Lao People\'s Democratic Republic','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '119','short_name' => 'LV','name' => 'Latvia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '120','short_name' => 'LB','name' => 'Lebanon','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '121','short_name' => 'LS','name' => 'Lesotho','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '122','short_name' => 'LR','name' => 'Liberia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '123','short_name' => 'LY','name' => 'Libyan Arab Jamahiriya','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '124','short_name' => 'LI','name' => 'Liechtenstein','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '125','short_name' => 'LT','name' => 'Lithuania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '126','short_name' => 'LU','name' => 'Luxembourg','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '127','short_name' => 'MO','name' => 'Macau','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '128','short_name' => 'MK','name' => 'Macedonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '129','short_name' => 'MG','name' => 'Madagascar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '130','short_name' => 'MW','name' => 'Malawi','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '131','short_name' => 'MY','name' => 'Malaysia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '132','short_name' => 'MV','name' => 'Maldives','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '133','short_name' => 'ML','name' => 'Mali','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '134','short_name' => 'MT','name' => 'Malta','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '135','short_name' => 'MH','name' => 'Marshall Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '136','short_name' => 'MQ','name' => 'Martinique','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '137','short_name' => 'MR','name' => 'Mauritania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '138','short_name' => 'MU','name' => 'Mauritius','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '139','short_name' => 'TY','name' => 'Mayotte','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '140','short_name' => 'MX','name' => 'Mexico','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '141','short_name' => 'FM','name' => 'Micronesia, Federated States of','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '142','short_name' => 'MD','name' => 'Moldova, Republic of','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '143','short_name' => 'MC','name' => 'Monaco','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '144','short_name' => 'MN','name' => 'Mongolia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '145','short_name' => 'ME','name' => 'Montenegro','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '146','short_name' => 'MS','name' => 'Montserrat','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '147','short_name' => 'MA','name' => 'Morocco','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '148','short_name' => 'MZ','name' => 'Mozambique','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '149','short_name' => 'MM','name' => 'Myanmar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '150','short_name' => 'NA','name' => 'Namibia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '151','short_name' => 'NR','name' => 'Nauru','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '152','short_name' => 'NP','name' => 'Nepal','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '153','short_name' => 'NL','name' => 'Netherlands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '154','short_name' => 'AN','name' => 'Netherlands Antilles','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '155','short_name' => 'NC','name' => 'New Caledonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '156','short_name' => 'NZ','name' => 'New Zealand','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '157','short_name' => 'NI','name' => 'Nicaragua','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '158','short_name' => 'NE','name' => 'Niger','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '159','short_name' => 'NG','name' => 'Nigeria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '160','short_name' => 'NU','name' => 'Niue','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '161','short_name' => 'NF','name' => 'Norfork Island','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '162','short_name' => 'MP','name' => 'Northern Mariana Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '163','short_name' => 'NO','name' => 'Norway','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '164','short_name' => 'OM','name' => 'Oman','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '165','short_name' => 'PK','name' => 'Pakistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '166','short_name' => 'PW','name' => 'Palau','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '167','short_name' => 'PA','name' => 'Panama','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '168','short_name' => 'PG','name' => 'Papua New Guinea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '169','short_name' => 'PY','name' => 'Paraguay','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '170','short_name' => 'PE','name' => 'Peru','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '171','short_name' => 'PH','name' => 'Philippines','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '172','short_name' => 'PN','name' => 'Pitcairn','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '173','short_name' => 'PL','name' => 'Poland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '174','short_name' => 'PT','name' => 'Portugal','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '175','short_name' => 'PR','name' => 'Puerto Rico','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '176','short_name' => 'QA','name' => 'Qatar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '177','short_name' => 'RE','name' => 'Reunion','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '178','short_name' => 'RO','name' => 'Romania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '179','short_name' => 'RU','name' => 'Russian Federation','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '180','short_name' => 'RW','name' => 'Rwanda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '181','short_name' => 'KN','name' => 'Saint Kitts and Nevis','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '182','short_name' => 'LC','name' => 'Saint Lucia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '183','short_name' => 'VC','name' => 'Saint Vincent and the Grenadines','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '184','short_name' => 'WS','name' => 'Samoa','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '185','short_name' => 'SM','name' => 'San Marino','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '186','short_name' => 'ST','name' => 'Sao Tome and Principe','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '187','short_name' => 'SA','name' => 'Saudi Arabia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '188','short_name' => 'SN','name' => 'Senegal','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '189','short_name' => 'RS','name' => 'Serbia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '190','short_name' => 'SC','name' => 'Seychelles','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '191','short_name' => 'SL','name' => 'Sierra Leone','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '192','short_name' => 'SG','name' => 'Singapore','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '193','short_name' => 'SK','name' => 'Slovakia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '194','short_name' => 'SI','name' => 'Slovenia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '195','short_name' => 'SB','name' => 'Solomon Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '196','short_name' => 'SO','name' => 'Somalia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '197','short_name' => 'ZA','name' => 'South Africa','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '198','short_name' => 'GS','name' => 'South Georgia South Sandwich Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '199','short_name' => 'ES','name' => 'Spain','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '200','short_name' => 'LK','name' => 'Sri Lanka','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '201','short_name' => 'SH','name' => 'St. Helena','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '202','short_name' => 'PM','name' => 'St. Pierre and Miquelon','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '203','short_name' => 'SD','name' => 'Sudan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '204','short_name' => 'SR','name' => 'Suriname','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '205','short_name' => 'SJ','name' => 'Svalbarn and Jan Mayen Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '206','short_name' => 'SZ','name' => 'Swaziland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '207','short_name' => 'SE','name' => 'Sweden','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '208','short_name' => 'CH','name' => 'Switzerland','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '209','short_name' => 'SY','name' => 'Syrian Arab Republic','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '210','short_name' => 'TW','name' => 'Taiwan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '211','short_name' => 'TJ','name' => 'Tajikistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '212','short_name' => 'TZ','name' => 'Tanzania, United Republic of','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '213','short_name' => 'TH','name' => 'Thailand','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '214','short_name' => 'TG','name' => 'Togo','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '215','short_name' => 'TK','name' => 'Tokelau','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '216','short_name' => 'TO','name' => 'Tonga','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '217','short_name' => 'TT','name' => 'Trinidad and Tobago','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '218','short_name' => 'TN','name' => 'Tunisia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '219','short_name' => 'TR','name' => 'Turkey','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '220','short_name' => 'TM','name' => 'Turkmenistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '221','short_name' => 'TC','name' => 'Turks and Caicos Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '222','short_name' => 'TV','name' => 'Tuvalu','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '223','short_name' => 'UG','name' => 'Uganda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '224','short_name' => 'UA','name' => 'Ukraine','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '225','short_name' => 'AE','name' => 'United Arab Emirates','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '226','short_name' => 'GB','name' => 'United Kingdom','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '227','short_name' => 'UM','name' => 'United States minor outlying islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '228','short_name' => 'UY','name' => 'Uruguay','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '229','short_name' => 'UZ','name' => 'Uzbekistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '230','short_name' => 'VU','name' => 'Vanuatu','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '231','short_name' => 'VA','name' => 'Vatican City State','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '232','short_name' => 'VE','name' => 'Venezuela','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '233','short_name' => 'VN','name' => 'Vietnam','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '234','short_name' => 'VG','name' => 'Virgin Islands (British)','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '235','short_name' => 'VI','name' => 'Virgin Islands (U.S.)','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '236','short_name' => 'WF','name' => 'Wallis and Futuna Islands','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '237','short_name' => 'EH','name' => 'Western Sahara','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '238','short_name' => 'YE','name' => 'Yemen','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '239','short_name' => 'YU','name' => 'Yugoslavia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '240','short_name' => 'ZR','name' => 'Zaire','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '241','short_name' => 'ZM','name' => 'Zambia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['id' => '242','short_name' => 'ZW','name' => 'Zimbabwe','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],

		]);
    }
}
